CREATE DATABASE IF NOT EXISTS idp;

USE idp;

DROP TABLE IF EXISTS Claim_Definition;
CREATE TABLE Claim_Definition (
	Name VARCHAR(512) NOT NULL PRIMARY KEY,
	Description VARCHAR(2048),
	PrivateKey TEXT NOT NULL,
	PublicParams TEXT NOT NULL,
	Digest TEXT NOT NULL,
	Sig TEXT NOT NULL,
	Cert TEXT NOT NULL,
	DateCreated TIMESTAMP NOT NULL	
);

DROP TABLE IF EXISTS Claim_Definition_Re_Key;
CREATE TABLE Claim_Definition_Re_Key (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(512) NOT NULL,
	ReKeyInfo TEXT NOT NULL
);

DROP TABLE IF EXISTS User;
CREATE TABLE User (
	Name VARCHAR(256) NOT NULL PRIMARY KEY,
	PubKeyCertificateFpr VARCHAR(256) NOT NULL, 
	PubKeyCertificate TEXT NOT NULL,
	DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Claim;
CREATE TABLE Claim (
	ClaimName VARCHAR(512) NOT NULL,
	UserName VARCHAR(256) NOT NULL,
	UserRandom TEXT NOT NULL,
	UserAnonId TEXT NOT NULL,
	IssueDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ClaimName, UserName)
);


